#### HF Losses in Ferrite Core Cross sections

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import mph
import mphsweepkit as msk
import numpy as np

Start the Comsol Server and load the model

In [3]:
# Start the COMSOL client
client = mph.start()

In [4]:
# Load the model
model = client.load('toroid_cross_section_initial.mph')

Create a CascadedSweepModel

In [5]:
# Create a CascadedSweepModel object
csm = msk.CascadedSweepModel(model, 'Study on Cross-Sections', show_param_names=True)

Initialized CascadedSweepModel
Study name: Study on Cross-Sections
Sweep Structure:
    - Geometry Sweep (BatchSweep) -> 'h_c', 'd_o', 'd_i'
      - Material Sweep (MaterialSweep) -> 'matsw.comp1.core1'
        - Excitation Sweep (Parametric) -> 'b_mean'
          - Frequency Sweep (Frequency)
Loop names: ['Geometry Sweep', 'Material Sweep', 'Excitation Sweep', 'Frequency Sweep']
Loop lengths: [1, 3, 4, 11]
Added 'geometry_idx' and 'internal_idx' columns to input_data. New shape: (132, 8)
--------------------------------
Data updated from MPh-model.
Input data shape: (132, 8)
Reset output data to shape of the input data: (132, 0)
Combined shape: (132, 8)

Change the material to 3F46

In [6]:
csm.set_material_sweep(sweep_name='Material Sweep', 
                       material_names=['matsw.comp1.core1'], 
                       material_values=[[2]], 
                       sweep_type="filled")

csm.input_data

Loop names: ['Geometry Sweep', 'Material Sweep', 'Excitation Sweep', 'Frequency Sweep']
Loop lengths: [1, 1, 4, 11]
Added 'geometry_idx' and 'internal_idx' columns to input_data. New shape: (44, 8)
--------------------------------
Data updated from MPh-model.
Input data shape: (44, 8)
Reset output data to shape of the input data: (44, 0)
Combined shape: (44, 8)
Added 'geometry_idx' and 'internal_idx' columns to input_data. New shape: (44, 8)

name,h_c,d_o,d_i,matsw.comp1.core1,b_mean,freq,geometry_idx,internal_idx
unit,mm,mm,mm,,mT,kHz,,
group,Geometry Sweep,Geometry Sweep,Geometry Sweep,Material Sweep,Excitation Sweep,Frequency Sweep,Indexing,Indexing
0,6.3,16.0,9.6,2.0,25.0,100.0,0,0
1,6.3,16.0,9.6,2.0,25.0,200.0,0,1
2,6.3,16.0,9.6,2.0,25.0,300.0,0,2
3,6.3,16.0,9.6,2.0,25.0,400.0,0,3
4,6.3,16.0,9.6,2.0,25.0,500.0,0,4
5,6.3,16.0,9.6,2.0,25.0,600.0,0,5
6,6.3,16.0,9.6,2.0,25.0,700.0,0,6
7,6.3,16.0,9.6,2.0,25.0,800.0,0,7
8,6.3,16.0,9.6,2.0,25.0,900.0,0,8
9,6.3,16.0,9.6,2.0,25.0,1000.0,0,9
10,6.3,16.0,9.6,2.0,25.0,1100.0,0,10
11,6.3,16.0,9.6,2.0,50.0,100.0,0,11
12,6.3,16.0,9.6,2.0,50.0,200.0,0,12
13,6.3,16.0,9.6,2.0,50.0,300.0,0,13
14,6.3,16.0,9.6,2.0,50.0,400.0,0,14
15,6.3,16.0,9.6,2.0,50.0,500.0,0,15
16,6.3,16.0,9.6,2.0,50.0,600.0,0,16
17,6.3,16.0,9.6,2.0,50.0,700.0,0,17
18,6.3,16.0,9.6,2.0,50.0,800.0,0,18
19,6.3,16.0,9.6,2.0,50.0,900.0,0,19
20,6.3,16.0,9.6,2.0,50.0,1000.0,0,20
21,6.3,16.0,9.6,2.0,50.0,1100.0,0,21
22,6.3,16.0,9.6,2.0,75.0,100.0,0,22
23,6.3,16.0,9.6,2.0,75.0,200.0,0,23
24,6.3,16.0,9.6,2.0,75.0,300.0,0,24
25,6.3,16.0,9.6,2.0,75.0,400.0,0,25
26,6.3,16.0,9.6,2.0,75.0,500.0,0,26
27,6.3,16.0,9.6,2.0,75.0,600.0,0,27
28,6.3,16.0,9.6,2.0,75.0,700.0,0,28
29,6.3,16.0,9.6,2.0,75.0,800.0,0,29
30,6.3,16.0,9.6,2.0,75.0,900.0,0,30
31,6.3,16.0,9.6,2.0,75.0,1000.0,0,31
32,6.3,16.0,9.6,2.0,75.0,1100.0,0,32
33,6.3,16.0,9.6,2.0,100.0,100.0,0,33
34,6.3,16.0,9.6,2.0,100.0,200.0,0,34
35,6.3,16.0,9.6,2.0,100.0,300.0,0,35
36,6.3,16.0,9.6,2.0,100.0,400.0,0,36
37,6.3,16.0,9.6,2.0,100.0,500.0,0,37
38,6.3,16.0,9.6,2.0,100.0,600.0,0,38
39,6.3,16.0,9.6,2.0,100.0,700.0,0,39
40,6.3,16.0,9.6,2.0,100.0,800.0,0,40
41,6.3,16.0,9.6,2.0,100.0,900.0,0,41
42,6.3,16.0,9.6,2.0,100.0,1000.0,0,42
43,6.3,16.0,9.6,2.0,100.0,1100.0,0,43

Set geometric sweep parameters to get circles with radii: 5, 10, 15 mm

In [7]:
    # Create arrays for the parameters based on the radii
h_c = np.array([10, 10, 10])  # height
d_o = np.array([14, 18, 22])  # outer diameter
d_i = np.array([10, 10, 10])  # inner diameter

# Set the parametric sweep for the 'Geometry Sweep'
csm.set_parametric_sweep(sweep_name='Geometry Sweep',
                         param_names=['h_c', 'd_o', 'd_i'], 
                         param_units=['mm', 'mm', 'mm'],
                         param_values=[h_c, 
                                       d_o, 
                                       d_i],
                         sweep_type="sparse")

csm.input_data

Loop names: ['Geometry Sweep', 'Material Sweep', 'Excitation Sweep', 'Frequency Sweep']
Loop lengths: [3, 1, 4, 11]
Added 'geometry_idx' and 'internal_idx' columns to input_data. New shape: (132, 8)
--------------------------------
Data updated from MPh-model.
Input data shape: (132, 8)
Reset output data to shape of the input data: (132, 0)
Combined shape: (132, 8)
Added 'geometry_idx' and 'internal_idx' columns to input_data. New shape: (132, 8)

name,h_c,d_o,d_i,matsw.comp1.core1,b_mean,freq,geometry_idx,internal_idx
unit,mm,mm,mm,,mT,kHz,,
group,Geometry Sweep,Geometry Sweep,Geometry Sweep,Material Sweep,Excitation Sweep,Frequency Sweep,Indexing,Indexing
0,10.0,14.0,10.0,2.0,25.0,100.0,0,0
1,10.0,14.0,10.0,2.0,25.0,200.0,0,1
2,10.0,14.0,10.0,2.0,25.0,300.0,0,2
3,10.0,14.0,10.0,2.0,25.0,400.0,0,3
4,10.0,14.0,10.0,2.0,25.0,500.0,0,4
...,...,...,...,...,...,...,...,...
127,10.0,22.0,10.0,2.0,100.0,700.0,2,39
128,10.0,22.0,10.0,2.0,100.0,800.0,2,40
129,10.0,22.0,10.0,2.0,100.0,900.0,2,41
130,10.0,22.0,10.0,2.0,100.0,1000.0,2,42
131,10.0,22.0,10.0,2.0,100.0,1100.0,2,43

Simulation

In [8]:
csm.simulate()

Batch directory for the geometric sweep set to: x:\Till_data\repositories\MPhSweepKit\examples\studies\toroid_cross_section\batch_data

Save the model with solution data:

In [10]:
model.save('toroid_cross_section_solved.mph')

Release the Client

In [11]:
client.remove(model)
client.clear()
client.disconnect()